[package]
name = "tron-lang"
version = "0.2.1"
edition = "2021"
authors = ["418e"]
description = "Open Source Programming Language"
documentation = "https://tron-lang.vercel.app/"
homepage = "https://tron-docs.vercel.app/"
repository = "https://github.com/jkl-org/Tron"
license = "Apache-2.0"


[dependencies]
num = "0.4.1"
rand = "0.8.5"